# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'logspout-gelf:$(build.buildId)'
  imageNameLatest: 'logspout-gelf:latest'

steps:
- script: docker build -t $(dockerIdKTHSE)/$(imageName) .
  displayName: 'docker build'

- script: docker login -u $(dockerId) -p $(dockerPassword)
  displayName: 'docker login'

- script: docker push $(dockerIdKTHSE)/$(imageName)
  displayName: 'Docker Push'

#- script: docker image tag $(dockerId)/$(imageName) $(dockerIdKTHSE)/$(imageName)
#  displayName: 'KTHse: tag image for push to KTHse Github'

- script: docker push $(dockerIdKTHSE)/$(imageName)
  displayName: 'KTHse: Push Docker image to KTHse DockerHub'
  
- script: docker image tag $(dockerId)/$(imageName) $(dockerIdKTHSE)/$(imageNameLatest)
  displayName: 'KTHse: tag image for push to KTHse Dockerhub'

- script: docker push $(dockerIdKTHSE)/$(imageNameLatest)
  displayName: 'KTHse: Push Docker image to KTHse Dockerhub'


 
